### ISSUE TITLE
is there a easy way for this plugin to work with flask-restful-api clases

### ISSUE THREAD

**Issue by codingsnippets** [acoomans/flask-autodoc#15]
I use flask-restful-api and I declare a class
this class has get, post, etc methods.
from flask.ext.restful import Resource
class A(Resource):
....def get():
........lots of code here

and I define the routes later, how would I make autodoc work in this case?

Thanks

**Comment by jwg4** [comment]
I would also like to see functionality like this (I use Flask-Restless rather than Flask-Restful-API). 
It seems that currently these extensions, which generate multiple endpoints, cannot be documented, as the endpoints will not be decorated, and that there is no way of including all endpoints without explicitly decorating them (based on looking at issue #1). Is this correct?

**Comment by lukeyeager** [comment]
I'm not sure how `Flask-Restful-API` or `Flask-Restless` work, but you can decorate the routes after the fact like this:
```python
for endpoint, function in app.view_functions.iteritems():
    app.view_functions[endpoint] = auto.doc()(function)
```
Does that get you what you need?

**Comment by codingsnippets** [comment]
this should fit my purpose, thanks. i will close it for now
